# Generated by Django 3.2.5 on 2021-07-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0002_auto_20210703_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='email',
            field=models.EmailField(default='nick@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='first_name',
            field=models.CharField(default='nick', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='owner',
            name='phone_number',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='owner',
            name='sur_name',
            field=models.CharField(default='nick', max_length=30),
            preserve_default=False,
        ),
    ]
