# Generated by Django 3.2.5 on 2021-07-03 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0002_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='photo',
            name='category',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='mypics.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='location',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='mypics.location'),
            preserve_default=False,
        ),
    ]
