# Generated by Django 3.2.5 on 2021-07-03 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0003_auto_20210703_1951'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='title',
            field=models.CharField(default='home', max_length=50),
            preserve_default=False,
        ),
    ]
