# Generated by Django 3.2.5 on 2021-07-03 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypics', '0004_location_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(default='food', max_length=50),
            preserve_default=False,
        ),
    ]
